#!/bin/sh

pushd . > /dev/null 2>&1
mkdir -p consul-template/bin
cd consul-template/bin
if [ ! -f docker ]; then
  curl -O https://get.docker.com/builds/Linux/x86_64/docker-1.9.0
  mv docker-1.9.0 docker
fi
if [ ! -f consul-template ]; then
  curl -O https://releases.hashicorp.com/consul-template/0.12.0/consul-template_0.12.0_linux_amd64.zip
  unzip consul-template_0.12.0_linux_amd64.zip
  rm consul-template_0.12.0_linux_amd64.zip
fi
popd > /dev/null 2>&1

docker rmi $(docker images -q --filter "dangling=true") > /dev/null 2>&1

for id in $(docker ps -a -q --filter="name=prometheus-demo-")
do
  docker rm --force $id > /dev/null 2>&1
done

docker build --tag="prometheus-demo-nodeapp:latest" ./nodeapp
docker build --tag="prometheus-demo-consul-template:latest" ./consul-template

if [[ $(docker ps -a -q --filter="name=prometheus-demo-promdash-data") == "" ]]; then
  docker create --name="prometheus-demo-promdash-data" \
    -v /tmp/prom \
    prom/promdash > /dev/null 2>&1
  docker run --rm \
    --volumes-from prometheus-demo-promdash-data \
    --env "DATABASE_URL=sqlite3:/tmp/prom/file.sqlite3" \
    prom/promdash ./bin/rake db:migrate > /dev/null 2>&1
fi

docker run --name="prometheus-demo-mongo" -d -p "27017:27017" mongo:3 > /dev/null 2>&1
docker run --name="prometheus-demo-mongodb-exporter" -d --link="prometheus-demo-mongo:mongo" lowstz/mongodb-exporter:latest -mongodb.uri=mongodb://mongo:27017 > /dev/null 2>&1
docker run --name="prometheus-demo-node-exporter" -d prom/node-exporter:latest > /dev/null 2>&1
docker run --name="prometheus-demo-container-exporter" -d -v /sys/fs/cgroup:/cgroup -v /var/run/docker.sock:/var/run/docker.sock prom/container-exporter > /dev/null 2>&1
docker run --name="prometheus-demo-consul-agent" -d --hostname="node1" -p "8400:8400" -p "8500:8500" -p "8600:53/udp" progrium/consul:latest -server -bootstrap -data-dir /data -ui-dir /ui > /dev/null 2>&1
docker run --name="prometheus-demo-consul-exporter" -d prom/consul-exporter -consul.server=consul:8500 > /dev/null 2>&1

# Register Prometheus exporters with Consul.
./register "container-exporter" 9104
./register "node-exporter" 9100
./register "mongodb-exporter" 9001
./register "consul-exporter" 9107

./scaleup nodeapp
./scaleup nodeapp

docker create --name="prometheus-demo-nginx-conf" -v /etc/nginx nginx:latest > /dev/null 2>&1
docker run --name="prometheus-demo-nginx" -d --volumes-from="prometheus-demo-nginx-conf" -p "8080:8080" nginx:latest > /dev/null 2>&1

docker create --name="prometheus-demo-consul-template" --link="prometheus-demo-consul-agent:consul" -v /var/run/docker.sock:/var/run/docker.sock --volumes-from="prometheus-demo-nginx-conf" prometheus-demo-consul-template:latest  > /dev/null 2>&1
docker cp ./consul-template/nginx.ctmpl prometheus-demo-consul-template:/tmp/nginx.ctmpl
docker start prometheus-demo-consul-template > /dev/null 2>&1

# Give Consul a chance to load config before starting Prometheus. If not then
# Prometheus will be unable to load the metrics services from Consul.
sleep 3

docker create --name="prometheus-demo-prom" \
  -p "9090:9090" \
  --link="prometheus-demo-consul-agent:consul" \
  prom/prometheus:latest > /dev/null 2>&1
docker cp ./prometheus.yml prometheus-demo-prom:/etc/prometheus/prometheus.yml
docker start prometheus-demo-prom > /dev/null 2>&1

docker run --name="prometheus-demo-promdash" \
  -d \
  -p "4000:3000" \
  --volumes-from prometheus-demo-promdash-data \
  --env DATABASE_URL=sqlite3:/tmp/prom/file.sqlite3 \
  prom/promdash > /dev/null 2>&1

docker ps -a --format "table {{.Names}}\t{{.ID}}\t{{.Status}}" --filter="name=prometheus-demo-"
